# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [ "feature-*" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run tests
      - name: Read the contents
        run: ls && cat index.html

